export const styleTypography = {
  marginTop: "30px",
  textAlign: "center",
  color: "#242331",
  fontFamily: "Nunito",
  fontSize: "35px",
  fontWeight: 700,
  lineHeight: "40px",
  width: "35%",
  paddingBottom: "40px",
};

export const styleTypography1 = {
  color: "#242331",
  fontFamily: "Nunito",
  fontSize: "30px",
  fontWeight: 700,
  lineHeight: "33px",
  textAlign: "center",
  width: "80%",
  height: "80px",
};
export const styleTypography2 = {
  color: "#797979",
  fontSize: "22px",
  fontWeight: 400,
  lineHeight: "34px",
  textAlign: "center",
  width: "90%",
  fontFamily: "Nunito",
  height: "150px",
};
export const styleTypography3 = {
  color: "#242331",
  fontSize: "18px",
  fontWeight: 700,
  lineHeight: "24px",
  textDecorationLine: "underline",
  fontFamily: "Nunito",
};
export const individualStyles = {
  1: {
    img1: {
      width: "120px",
      height: "42px",
      flexShrink: 0,
      top: "57px",
      objectFit: "cover",
      left: "227px",
      position: "absolute",
      zIndex: "3",
    },

    img2: {
      width: "267px",
      height: "174px",
      flexShrink: 0,
      zIndex: 2,
      borderRadius: "10px",

      paddingLeft: "54px",
      marginTop: "20px",
      top: "8px",
      left: "21px",
      position: "absolute",
    },
    img3: {
      width: "160px",
      height: "140px",
      zIndex: 3,
      flexShrink: 0,
      marginTop: "96px",
      position: "absolute",
    },
  },
  2: {
    img1: {
      width: "260px",
      height: "202px",
      flexShrink: 0,
      zIndex: 1,
      top: "28px",
      left: "45px",
      position: "absolute",
    },
    img2: {
      position: "absolute",
      width: "198px",
      height: "130px",
      flexShrink: 0,
      zIndex: "3",
      left: "200px",
      top: "136px",
    },
    img3: { display: "none" },
  },
  3: {
    img1: {
      width: "118px",
      height: "90px",
      flexShrink: 0,
      zIndex: 4,
      top: "56px",
      left: "254px",
    },
    img2: {
      width: "118px",
      height: "90px",
      flexShrink: 0,
      zIndex: 4,
      position: "absolute",
      left: "49px",
      top: "139px",
    },
    img3: {
      width: "260px",
      height: "170px",
      flexShrink: 0,
      borderRadius: "10px",
      zIndex: 1,
      position: "absolute",
      left: "72px",
      top: "45px",
    },
  },
  4: {
    img1: {
      width: "80%",
      height: "200px",
      position: "absolute",
      left: "10%",
      top: "30px",
    },
    img2: { display: "none" },
    img3: { display: "none" },
  },
  5: {
    img1: {
      width: "80%",
      height: "200px",
      position: "absolute",
      left: "10%",
      top: "30px",
    },
    img2: { display: "none" },
    img3: { display: "none" },
  },
  6: {
    img1: {
      width: "80%",
      height: "200px",
      position: "absolute",
      left: "10%",
      top: "30px",
    },
    img2: { display: "none" },
    img3: { display: "none" },
  },
};
